### ISSUE TITLE
issues with the boss

### ISSUE THREAD

**Issue by Shadowy1984** [nickc01/Ancient-Aspid#2]
In the first fight, the boss does not wake up, and in the Godhome fight, the boss flies into the bottom left corner of the arena. please fix!!!

**Comment by nickc01** [comment]
Could you send me your ModLog.txt and Player.Log files? They contain more information that will allow me to see what's going on. You can find them located at "C:\Users\USERNAME_HERE\AppData\LocalLow\Team Cherry\Hollow Knight" if you are on Windows

**Comment by Shadowy1984** [comment]
It must have been Pale Court, actually. Luckily you patched it.
