### ISSUE TITLE
pantheon

### ISSUE THREAD

**Issue by PLMMJ-FH** [nickc01/Ancient-Aspid#6]
Does it show up in pantheons

**Comment by nickc01** [comment]
Currently, the modded boss doesn't show up in the pantheons. However, you can make it work with the Custom Pantheon mod:

https://github.com/ygsbzr/HollowKnight.CustomPantheon

You can modify the PantheonRooms section in it's Global Settings to load the Ancient Aspid in a custom pantheon. The scene names you can use are these:

Attuned Arena Scene = "GG_Ancient_Aspid"
Ascended Arena Scene = "GG_Ancient_Aspid_V"
Radiant Arena Scene = "GG_Ancient_Aspid_RAD"

**Comment by PLMMJ-FH** [comment]
OK thanks. I was asking for the sake of custom pantheons.

**Comment by PLMMJ-FH** [comment]
Thanks, I was asking for the sake of making a custom pantheon.
